<?php
/*
Detailed Summary: Integrating HTML in PHP

PHP is designed to work seamlessly with HTML, allowing you to create dynamic web pages. Here are the main methods to integrate HTML and PHP:

1. Embedding PHP in HTML
    - Write your HTML as usual and insert PHP code where you need dynamic content.
    - Example:
*/
$username = "Alice";
$isLoggedIn = true;
?>
<!DOCTYPE html>
<html>
<head>
     <title>Integrating HTML in PHP</title>
</head>
<body>
     <h2>1. Embedding PHP in HTML</h2>
     <p>Welcome, <?php echo $username; ?>!</p>

     <h2>2. Echoing HTML from PHP</h2>
     <?php
     // Outputting HTML using echo
     echo "<p>This is a paragraph generated by PHP.</p>";
     ?>

     <h2>3. Mixing PHP and HTML (Alternative Syntax)</h2>
     <?php if ($isLoggedIn): ?>
          <p>Hello, <?php echo $username; ?>! You are logged in.</p>
     <?php else: ?>
          <p>Please log in.</p>
     <?php endif; ?>

     <h2>4. Using Heredoc for Large HTML Blocks</h2>
     <?php
     $htmlBlock = <<<HTML
     <div style="border:1px solid #ccc; padding:10px;">
          <h3>Heredoc Example</h3>
          <p>This block of HTML is stored in a PHP variable using heredoc syntax.</p>
     </div>
     HTML;
     echo $htmlBlock;
     ?>

     <h2>Best Practices</h2>
     <ul>
          <li>Keep PHP logic and HTML presentation separate when possible.</li>
          <li>Use templates or frameworks for larger projects.</li>
          <li>Sanitize all output to prevent XSS attacks.</li>
     </ul>
</body>
</html>